dist: xenial
language: node_js
node_js:
- "11.1"
pandoc_version: 2.2

# S: Build Lifecycle
install:
  - wget https://github.com/jgm/pandoc/releases/download/2.4/pandoc-2.4-1-amd64.deb 
  - sudo dpkg -i ./pandoc-2.4-1-amd64.deb
  - npm install -g hexo-cli
  - npm install -f
#  - npm install hexo-generator-searchdb --save

#before_script:

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Peijun Zhu"
  - git config user.email "zpj@gatech.edu"
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

env:
  global:
    - GH_REF: github.com/AlgoGentlemen/algogentlemen.github.io.git
    - secure: "pr/WbceAU6qIzFjpyimDbd1GneZcyn4r7KAdbDxCqoXmExuWulLJkAXkpsnjTYtmCbssFlrZb3Iiwax0AXIQXZSmgM96Va4jaZBxvdIhNYyB9vQ+e/i7YlviHA9oFtIjUSdiXCW5JA4FWPS/O15lmyVDcTINvB/rgBO6GFOYcKZ/2a5O1k336AO66NWBYIoQGsCAnXzExzmKAGt6KGQbpje4bPm/+Txv9kAPQOf7dcyL3qV30SE6wzLNFPqNyjr39iaA/DR9WwZKq3AxNVyehlJ5XqPJcoYH8nHaH9rvtv49el+nDSCTD+62pCrgjNaIFR5onn54khJ4qJZSbh9Njc1FUWv9+0CqZdn3KogkZzd5W6+rH0knuFbeK6RfgCQri7eCiwhcCXerZ+FHsCjjqxhLxVgds1VXDcckje78L446ExAXSFL2d9gj4BD0CfpHFbFhhDKnQHvb6OYRlTK5UEWL50dpN2uLBWCstuCN1tuqELcFept8FVKoPOpRSarLXVegiD6Cv82b92maYIBN/9HMzhTjYIod/Z5aD7OEMFOCs4FIVEgS6HgLSh8197l8B1vU/uFfxGYhko3/b9E6OVAd1cA4CWI/Pc3Di7WzMbpmffXd17Q5Yo+A//SfrzYlXVwB8pcb5IXl3SWL/jKqxNyRVG2GWQXiN1okdwuf83E="
