dist: xenial
language: node_js
node_js:
- "11.1"
pandoc_version: 2.2

# S: Build Lifecycle
install:
  - wget https://github.com/jgm/pandoc/releases/download/2.4/pandoc-2.4-1-amd64.deb 
  - sudo dpkg -i ./pandoc-2.4-1-amd64.deb
  - npm install -g hexo-cli
  - npm install -f
#  - npm install hexo-generator-searchdb --save

#before_script:

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Peijun Zhu"
  - git config user.email "zpj@gatech.edu"
  - git add .
  - git commit -m "Update Blog"
  - git push --force --quiet "https://${GIT_HUB_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

env:
  global:
    - GH_REF: github.com/AlgoGentlemen/algogentlemen.github.io.git
    - secure: "aMW2WI1MqFsKozQryJCo4Zb/tGeDiCrIunJQeDXAoMoZ6l+updWu8CZUwe4nMngKnftLZT3yxBy8GS9V4n+i4YEMBxNrKsrwuR3192KvZ6w93FSHQDFHqw7JtXESG2rx8e453ZoUZOUwsRFBRY87rv7mZTCSPv1WwnYOOfH/MfW1YW0S2lbEPszUaeb5v+nJlX1UnxoZlSryla+yaQNUT1Ao1jcizFb7YjwjzxFb91EV+1CEwuytE0PjguphHxYLH1HI2DhtrH25KHYB6yC8McSO3cE0k+zJkr9YJpHFpiqHmM3uqKPgTs7uyu7pbiLmkKmcKLXhWsT9wlTpnIoJH+EHqLgWQDmy+Rby8bNJy0uWW4yKO/VXHdx63aI+Rz9YgoBgZ3Miw9wM87yPRFu9T/jRPgw3pLHBlHQVXPnWzDTftZdEcSm0kMV6u7SsAl2GLSbNfgy26hAophrwh86ixKnokhHn0xQfGxVqspbuYJqLvNnrko2JB12BKo8ttTUc43mbIr12clQMoRglvCdr2Gsn9P8Plpb54MIEndYowTIdhNMCjHgf5AOEVnAZQKb9XA3boOSPJvZkyOe5pEBpOFf3qV/MVodlKhGbCMX5ZVPawVKeQcdYbbJCdK8lmjFO84bUxI5mpeJgQSbZSPCtdR59m7cbAMZOJFGU3PSyTD8="
